### ISSUE TITLE
Idea: Add github-conflict-like Viewer when observations is different

### ISSUE THREAD

**Issue by WangLaoK** [gowerc/diffdf#15]
Hi Craig & Kieran,

This is Hans, I wanna make an idea with `diffdf `package.
When I got to compare with two datasets with the same Observations(rows) and different Variables(columns), `diffdf` serves as an excellent tools. However, when I compared with different Obs datasets, `diffdf` may not be as comfortable as I wished. I have the check which rows in two dataset is different. So I recommend a github-conflict Viewer to solve this plight.
Just somehow like below
![44888567-71788b80-ad04-11e8-8bf9-be1957fe8ab6](https://user-images.githubusercontent.com/18552915/44902906-c97fb400-ad3d-11e8-8310-56b1842bd385.png)
I am sorry for forsake my saying, as for rows difference between 2 datasets, `diffobj` may have its advantages. So I may combine this two tools.(The attribution difference is prior for `diffdf` package.)

Yours,
Hans

**Comment by kieranjmartin** [comment]
Hi Hans,

We are looking into an html like viewer. For the difference in rows, rather than a row by row comparison, we do currently rely on row number, but could theoretically add this via variable.

I would note that diffobj as designed does not do what you might expect. From reading it's vignette, it compares the printed output of one R object with another, but the print method can be quite misleading as to the actual values of an object. 

I think the next big step for us is making the outputs more flexible and nice, something like this may be a good idea, we will have to experiment! Thanks for the feedback!

**Comment by HustlerQian** [comment]
Hi Kieran & Craig,

Thank you for you two kind reply. Somehow, there may be situation to have the different rows in two datasets. Like the picture above, the `APD_1st ` dataframe includes the Obs that `APD` doesn't. So I do recommend this **SidebySide** layout for shown. 

Also I do agree with the your plan which makes outputs more flexible and nice, I find a [htmlwidget] (https://github.com/muschellij2/diffr) for _R_(or _JS_) called `diffr` which is my favourite tool for comparing two text file. Hope it may help with your package and wish you two guys the best at work.

(I find that this package is external, so I change the snapshot with mosaic)

**Comment by gowerc** [comment]
Thanks for the information, will definietly take it into consideration when we build our html viewer.

I am going to close this ticket though as there is nothing explicit to work on here which isn't covered in our other open tickets.
