### ISSUE TITLE
keep an eye on waldo

### ISSUE THREAD

**Issue by kieranjmartin** [gowerc/diffdf#63]
https://github.com/r-lib/waldo is Hadley Wickham's new package for comparing objects. From testing it, it's basically an enchanced all.equal, and isn't truly comparable to diffdf, but it is likely to be a used tool, and something we could get ideas from. In particular, it makes use of coloured console output

**Comment by gowerc** [comment]
did some benchmarking,  I think because waldo tries to colour code every difference it is super inefficient especially for long character strings. On a dataset with 500k observations and 40 variables (all character) diffdf took 4 seconds where as I killed waldo after waiting for over 8 minutes. 

I defo don't think the colour coding is worth the time penalty
